### Configuration parameters ###
NUMBER_OF_DATANODE = 2
DEPLOY_Geonetwork = false
### end of Configuration parameters ###

Vagrant.configure("2") do |config|
	config.vm.define "namenode" do |namenode|
		namenode.vm.box = "generic/debian9"
		namenode.vm.network "public_network", bridge:"enp1s0", use_dhcp_assigned_default_route: true
		namenode.vm.provision "shell", inline: <<-SHELL
			systemctl stop resolvconf
			echo "nameserver 10.34.192.61" >> /etc/resolv.conf
			echo "nameserver 10.34.192.62" >> /etc/resolv.conf
		SHELL
		namenode.vm.hostname = "namenode"
		namenode.vm.network :private_network, ip: "10.0.0.10"
		namenode.vm.provision "ansible" do |ansible|
			ansible.playbook = "../../playbook/install-namenode.yml"
		end
		if DEPLOY_Geonetwork == true
			namenode.vm.provision "ansible" do |ansible|
				ansible.playbook = "../../playbook/install-geonetwork-by-git.yml"
			end
		end
	end

	# Number of datanode
	N = NUMBER_OF_DATANODE
	(1..N).each do |machine_id|
		config.vm.define "datanode#{machine_id}" do |machine|
			machine.vm.box = "generic/debian9"
			machine.vm.network "public_network", bridge:"enp1s0", use_dhcp_assigned_default_route: true
			machine.vm.provision "shell", inline: <<-SHELL
				systemctl stop resolvconf
				echo "nameserver 10.34.192.61" >> /etc/resolv.conf
				echo "nameserver 10.34.192.62" >> /etc/resolv.conf
			SHELL
			machine.vm.hostname = "datanode#{machine_id}"
			machine.vm.network :private_network, ip: "10.0.0.1#{machine_id}"
			machine.vm.provision "ansible" do |ansible|
				ansible.playbook = "../../playbook/install-datanode.yml"
			end
		end
	end
end